#!/usr/bin/env bash

if [ ! -f "components" ]; then
  mkdir components
fi

if [ ! -f "components/aminui" ]; then
  mkdir components/adminui
  git clone https://github.com/robtweed/wc-admin-ui components/adminui
fi

if [ ! -f "components/leaflet" ]; then
  mkdir components/leaflet
  git clone https://github.com/robtweed/wc-leaflet components/leaflet
fi

if [ ! -f "components/d3" ]; then
  mkdir components/d3
  git clone https://github.com/robtweed/wc-admin-ui components/d3
fi

if [ ! -f "mg-webComponents.js" ]; then
  git clone https://github.com/robtweed/mg-webComponents
  mv mg-webComponents/mg-webComponents.js .
  sudo rm -r mg-webComponents
fi

if [ ! -f "index.html" ]; then
  mv mgweb-server-utils/index.html .
fi

