#!/usr/bin/env bash


if [ ! -d "conduit-wc" ]; then
  git clone https://github.com/robtweed/wc-conduit
  if [ ! -d "components" ]; then
    mv wc-conduit/components .
  else
    mv wc-conduit/components/conduit components
  fi
  mv wc-conduit/conduit-wc .
  sudo rm -r wc-conduit
fi

if [ ! -f "mg-webComponents.js" ]; then
  git clone https://github.com/robtweed/mg-webComponents
  mv mg-webComponents/mg-webComponents.js .
  sudo rm -r mg-webComponents
fi

if [ ! -f "index.html" ]; then
  mv mgweb-server-utils/index.html .
fi